services:
  postgres:
    image: postgres:16-alpine
    container_name: marketplace-postgres
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marketplace"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: marketplace-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: marketplace-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: marketplace-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

  mailhog:
    image: mailhog/mailhog:latest
    container_name: marketplace-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI

  dbgate:
    image: dbgate/dbgate:latest
    container_name: marketplace-dbgate
    ports:
      - "3100:3000"  # Web UI
    environment:
      CONNECTIONS: pg
      LABEL_pg: Marketplace DB
      SERVER_pg: postgres        # tên service trong compose network
      PORT_pg: 5432
      USER_pg: marketplace
      PASSWORD_pg: marketplace
      DATABASE_pg: marketplace
      ENGINE_pg: postgres@dbgate-plugin-postgres
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - dbgate_data:/root/.dbgate

volumes:
  postgres_data:
  redis_data:
  dbgate_data:
